apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: music
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- pvc.yaml
images:
- name: ghcr.io/dubnubdubnub/navidrome-s3
  newName: ghcr.io/dubnubdubnub/navidrome-s3
  newTag: f8f8f60234bb0ca92bc706ac7c0405d34adb5914
